Unify full_replace and non-full_replace insert
terminusdb/terminusdb pull request #1095
Opened 2022-04-08 12:43 UTC by spl

* `full_replace` schema insert was using a different code path, which
  lead to a strange error when the same `@id` is used in multiple types.
* This change makes instance and schema insert use the same code paths
  for both `full_replace` and not.
* Rename some `json_read` predicates for clarity.
* Add `json_read_list_stream_head` and `json_read_tail_stream` for
  reading the first term from a stream and then the rest.
* Add unit tests to `json_read` predicates.
* Fixes #1063

2022-04-08 14:44 UTC, matko requested changes
I like the approach to unify stream and list reading with the head/tail stuff.

2022-04-08 14:44 UTC, matko commented on src/core/api/api_document.pl
> +    % Read a new context from the stream and replace the existing one.
should this not cut?

2022-04-08 14:44 UTC, matko commented on src/core/api/api_document.pl
> +                         ensure_transaction_has_builder(Graph_Type, Transaction),
you should ensure the builder before you prepare the full replace as that already potentially uses the builder.

2022-04-12 10:00 UTC, spl commented
Okay, this is ready to go now. We figured out that the failing “Check / Python client tests is due to <https://github.com/terminusdb/terminusdb/issues/1099>.

2022-04-12 10:56 UTC, matko approved these changes

2022-04-12 10:56 UTC, merged