Allow loading of trig files
terminusdb/terminusdb pull request #1410
Opened 2022-08-25 14:16 UTC by GavinMendelGleason

2022-08-25 14:22 UTC, rrooij commented
Can you provide a simple integration test? :smile: Something very simple like inserting a `trig` in a schemaless DB.

2022-08-25 15:45 UTC, matko requested changes

2022-08-25 15:45 UTC, matko commented on src/core/triple/literals.pl
> +    ;   format(user_error,'Warning: ignoring graph ~q~n', [G]),
Please use `json_log_warning_formatted` instead so it works properly with different logging backends we set up.

2022-08-25 15:52 UTC, rrooij commented
Made a simple integration test

2022-08-30 09:33 UTC, matko requested changes

2022-08-30 09:33 UTC, matko commented on src/core/triple/literals.pl
> +    ;   json_log_error_formatted('Warning: ignoring graph ~q~n', [G]),
please use `json_log_warning_formatted` as it is not an error.

2022-08-31 15:36 UTC, matko approved these changes

2022-08-31 15:36 UTC, merged