Small changes
terminusdb/terminusdb pull request #827
Opened 2021-12-02 16:48 UTC by luke-feeney

2021-12-02 17:02 UTC, OJ423 requested changes
Looks great and reads really well - spotted some errors:

Last sentence of the first section (A toolkit for building) - 
Reads: If you want to build a data-intensive applications, TerminusDB and TerminusX are right for you.
Should be: If you want to build data-intensive applications, TerminusDB and TerminusX are right for you.

Documentation (bottom of the page) link is currently - https://terminusdb.com/docs/terminusdb/

Should be: https://terminusdb.com/docs/

Release notes point to your repository: https://github.com/luke-feeney/terminusdb/blob/main/docs/RELEASE_NOTES.md

Should be: https://github.com/terminusdb/terminusdb/blob/main/docs/RELEASE_NOTES.md

2021-12-02 17:23 UTC, GavinMendelGleason approved these changes

2021-12-10 23:12 UTC, GavinMendelGleason approved these changes

2021-12-13 12:00 UTC, matko approved these changes
Kinda confused that we're using HTML tags in a markdown file, but as this is apparently already existing practice, let's just go with it for now.

2021-12-13 12:00 UTC, OJ423 approved these changes

2021-12-13 12:00 UTC, merged